# Generated by Django 3.1.7 on 2021-03-02 17:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Python\\projects\\foodboxes_project\\static'), upload_to='items'),
        ),
    ]
