# Generated by Django 3.1.7 on 2021-02-24 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('1', 'на модерации'), ('2', 'опубликован'), ('3', 'отклонен')], max_length=64)),
            ],
        ),
    ]
